### Create a doctor
POST http://localhost:3000/doctors
Content-Type: application/json

{
  "username": "john.doe",
	"firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com"
}

### Create a slot
POST http://localhost:3000/slots
Content-Type: application/json

{
  "startTime": "2025-03-03T10:00:00.000Z",
  "endTime": "2025-03-03T11:00:00.000Z",
  "doctorId": "144907df-89be-4c6e-8cba-7704bfbc7136",
  "recurrenceType": "DAILY"
}

### Get available slots
GET http://localhost:3000/doctors/144907df-89be-4c6e-8cba-7704bfbc7136/available_slots?startDate=2025-04-04&endDate=2025-04-05

### Create an appointment
POST http://localhost:3000/slots/c05ae50c-af6b-4a3c-bdfd-361d8a9bc8a1/book
Content-Type: application/json

{
  "startTime": "2025-04-04T10:00:00.000Z",
  "endTime": "2025-04-04T10:30:00.000Z",
  "patientEmail": "john.doe@example.com"
}

### Get booked slots
GET http://localhost:3000/doctors/144907df-89be-4c6e-8cba-7704bfbc7136/booked
