services:

  service-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=backend-developer-test
      - POSTGRESQL_REPLICATION_USE_PASSFILE="no"
    volumes:
      - postgres_data:/bitnami/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_URL=postgresql://docker:docker@service-pg:5432/backend-developer-test
      - PORT=3000
    depends_on:
      - service-pg

volumes:
  postgres_data:
