services:

  service-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=backend-developer-test
      - POSTGRESQL_REPLICATION_USE_PASSFILE="no"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
